<?php

namespace Database\Seeders;

use App\Models\Admin;
use App\Models\Place;
use App\Models\Event;
use App\Models\BlogPost;
use App\Models\User;
use App\Models\Review;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        $admin = Admin::factory()->create([
            'email' => 'admin@vibespot.com',
            'display_name' => 'VibeSpot Editorial'
        ]);

        // Create a demo user for seeding reviews
        $user = User::create([
            'email' => 'demo@vibespot.com',
            'display_name' => 'Arif Rahman',
            'password_hash' => bcrypt('password'),
            'is_active' => true,
        ]);

        $user2 = User::create([
            'email' => 'nadia@vibespot.com',
            'display_name' => 'Nadia Hossain',
            'password_hash' => bcrypt('password'),
            'is_active' => true,
        ]);

        $user3 = User::create([
            'email' => 'karim@vibespot.com',
            'display_name' => 'Karim Uddin',
            'password_hash' => bcrypt('password'),
            'is_active' => true,
        ]);

        // ─── REAL DHAKA PLACES ───
        $places = [
            [
                'name' => 'North End Coffee Roasters',
                'category' => 'Food & Drinks',
                'area_name' => 'Gulshan',
                'area_zone' => 'DNCC',
                'address' => 'Road 103, Gulshan 2, Dhaka 1212',
                'description' => 'A premium third-wave coffee house in the heart of Gulshan. North End sources single-origin beans from Sylhet and Rangamati hill tracts, roasts in-house, and serves precision pour-overs alongside artisan pastries. The minimalist industrial interior — exposed brick, warm wood, Edison bulbs — draws remote workers, creatives, and coffee purists alike.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$$$',
                'average_rating' => 4.7,
                'total_reviews' => 342,
                'tags' => ['Coffee', 'WiFi', 'Laptop-Friendly', 'Specialty Brews'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Chillox',
                'category' => 'Food & Drinks',
                'area_name' => 'Dhanmondi',
                'area_zone' => 'DSCC',
                'address' => 'Road 27, Dhanmondi, Dhaka 1205',
                'description' => 'An iconic Dhanmondi café nestled beside Dhanmondi Lake. Known for its signature mango smoothies, continental breakfast platters, and lakeside terrace seating. A go-to for university students from nearby campuses and young professionals looking for a relaxed weekend brunch.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$$',
                'average_rating' => 4.5,
                'total_reviews' => 528,
                'tags' => ['Lakeside', 'Brunch', 'Student-Friendly', 'Outdoor Seating'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Star Kabab & Restaurant',
                'category' => 'Food & Drinks',
                'area_name' => 'Old Dhaka',
                'area_zone' => 'DSCC',
                'address' => 'Nazira Bazaar, Bangsal Road, Dhaka 1100',
                'description' => 'A legendary Old Dhaka institution serving the finest Mughlai cuisine for over five decades. Their mutton rezala, beef tehari, and the famous naan-e-kabab are not just meals — they are cultural experiences. The no-frills communal dining atmosphere is part of the charm.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1589187151032-573a91317445?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$',
                'average_rating' => 4.8,
                'total_reviews' => 1205,
                'tags' => ['Mughlai', 'Heritage', 'Biriyani', 'Legendary'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Lalbagh Fort',
                'category' => 'Landmarks & Heritage',
                'area_name' => 'Old Dhaka',
                'area_zone' => 'DSCC',
                'address' => 'Lalbagh Road, Dhaka 1211',
                'description' => 'A 17th-century Mughal fort complex begun by Prince Muhammad Azam in 1678. Though never completed, the fort contains the Mosque of Shaista Khan, the Tomb of Bibi Pari, and a museum. The well-maintained gardens offer a serene green haven amidst Old Dhaka\'s busy lanes. A must-visit for history enthusiasts and photographers.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1599307733285-930438c64264?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$',
                'average_rating' => 4.6,
                'total_reviews' => 890,
                'tags' => ['Mughal', 'History', 'Photography', 'Museum'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Ahsan Manzil (Pink Palace)',
                'category' => 'Landmarks & Heritage',
                'area_name' => 'Old Dhaka',
                'area_zone' => 'DSCC',
                'address' => 'Kumartoli, Dhaka 1100',
                'description' => 'The iconic Pink Palace on the banks of the Buriganga River — once the seat of the Nawabs of Dhaka. Now a museum, Ahsan Manzil showcases the grandeur of Bengal\'s aristocratic past through 23 galleries filled with portraits, furniture, and artefacts. The palace glows magnificently under evening floodlights.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1623055938555-520e53a0058b?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$',
                'average_rating' => 4.7,
                'total_reviews' => 760,
                'tags' => ['Palace', 'Nawab', 'Buriganga', 'Museum'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Hatirjheel Lakefront',
                'category' => 'Outdoors',
                'area_name' => 'Tejgaon',
                'area_zone' => 'DNCC',
                'address' => 'Hatirjheel Bridge, Tejgaon, Dhaka',
                'description' => 'Dhaka\'s most ambitious urban water body project spanning 302 acres. The beautifully lit pedestrian walkways, cycling paths, and the iconic bridge make Hatirjheel the city\'s favourite evening hangout. Street food vendors, boat rides during monsoon, and spectacular sunset views draw thousands daily.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1563200155-0df75a0655fc?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$',
                'average_rating' => 4.4,
                'total_reviews' => 1580,
                'tags' => ['Lake', 'Walking', 'Cycling', 'Night Views', 'Free Entry'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Dhanmondi Lake Park',
                'category' => 'Outdoors',
                'area_name' => 'Dhanmondi',
                'area_zone' => 'DSCC',
                'address' => 'Road 15, Dhanmondi, Dhaka 1205',
                'description' => 'The green lung of Dhanmondi — a serene park surrounding the iconic lake. Popular for morning joggers, evening strollers, and couples. The recently renovated walkways, kids\' play zones, and lakeside benches make it Dhaka\'s most cherished urban park. The Rabindra Sarobar area hosts cultural events year-round.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1632961745430-2fc391b74f4b?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$',
                'average_rating' => 4.3,
                'total_reviews' => 2100,
                'tags' => ['Lake', 'Park', 'Jogging', 'Family-Friendly', 'Free Entry'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Dhaka Art Center',
                'category' => 'Culture',
                'area_name' => 'Dhanmondi',
                'area_zone' => 'DSCC',
                'address' => 'Road 6, Dhanmondi, Dhaka 1205',
                'description' => 'Dhaka\'s premier contemporary art space. The center hosts rotating exhibitions by emerging Bangladeshi artists, monthly open-mic nights, documentary film screenings, and art workshops. The gallery café on the second floor serves excellent espresso. A cultural anchor for the Dhanmondi creative community.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$$',
                'average_rating' => 4.5,
                'total_reviews' => 310,
                'tags' => ['Art', 'Gallery', 'Exhibitions', 'Workshops'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Gulshan DCC Market Food Court',
                'category' => 'Food & Drinks',
                'area_name' => 'Gulshan',
                'area_zone' => 'DNCC',
                'address' => 'Gulshan 1 Circle, Dhaka 1212',
                'description' => 'A vibrant local hub for street food lovers. From hot momos to grilled chicken and fresh juices, this food court captures the fast-paced urban dining spirit of Gulshan.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$',
                'budget_label' => 'Low-Medium',
                'budget_range' => '150-500',
                'operating_hours' => [
                    'Monday' => '11:00 AM - 10:00 PM',
                    'Tuesday' => '11:00 AM - 10:00 PM',
                    'Wednesday' => '11:00 AM - 10:00 PM',
                    'Thursday' => '11:00 AM - 10:30 PM',
                    'Friday' => '11:00 AM - 10:30 PM',
                    'Saturday' => '11:00 AM - 10:00 PM',
                    'Sunday' => '11:00 AM - 10:00 PM',
                ],
                'tags' => ['Street Food', 'Budget', 'Gulshan', 'Evening'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Bashundhara City Shopping Mall',
                'category' => 'Shopping',
                'area_name' => 'Panthapath',
                'area_zone' => 'DNCC',
                'address' => 'Panthapath, Dhaka',
                'description' => 'One of the largest shopping malls in South Asia, featuring over 2,500 retail stores, a massive food court, a multiplex cinema, and a theme park.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$$',
                'budget_label' => 'Medium-High',
                'budget_range' => '500-15000',
                'operating_hours' => [
                    'Monday' => '10:00 AM - 8:00 PM',
                    'Tuesday' => '10:00 AM - 8:00 PM',
                    'Wednesday' => '10:00 AM - 8:00 PM',
                    'Thursday' => '10:00 AM - 8:00 PM',
                    'Friday' => '10:00 AM - 8:00 PM',
                    'Saturday' => '10:00 AM - 8:00 PM',
                    'Sunday' => 'Closed',
                ],
                'average_rating' => 4.3,
                'total_reviews' => 3200,
                'tags' => ['Shopping', 'Cinema & Screenings', 'Family', 'Ice Rink', 'Food Court'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'National Parliament House',
                'category' => 'Landmarks & Heritage',
                'area_name' => 'Sher-e-Bangla Nagar',
                'area_zone' => 'DSCC',
                'address' => 'Sher-e-Bangla Nagar, Dhaka 1207',
                'description' => 'Designed by legendary architect Louis Kahn, the Jatiya Sangsad Bhaban is widely considered one of the 20th century\'s most significant works of architecture. The brutalist concrete complex, set within a vast artificial lake and landscaped grounds, is both a functioning parliament and an architectural pilgrimage site. The surrounding grounds are open for public walks.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1518005020251-582c78276e5f?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$',
                'budget_label' => 'Free',
                'budget_range' => '0-0',
                'operating_hours' => [
                    'Monday' => '9:00 AM - 5:00 PM',
                    'Tuesday' => '9:00 AM - 5:00 PM',
                    'Wednesday' => '9:00 AM - 5:00 PM',
                    'Thursday' => '9:00 AM - 5:00 PM',
                    'Friday' => 'Closed',
                    'Saturday' => 'Closed',
                    'Sunday' => '9:00 AM - 5:00 PM',
                ],
                'average_rating' => 4.9,
                'total_reviews' => 1850,
                'tags' => ['Architecture', 'Louis Kahn', 'Brutalist', 'Photography'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Star Cineplex',
                'category' => 'Cinema & Screenings',
                'area_name' => 'Panthapath',
                'area_zone' => 'DNCC',
                'address' => 'Level 8, Bashundhara City, Panthapath, Dhaka',
                'description' => 'The first multiplex cinema in Bangladesh. Offering international standard movie viewing experience with multiple screens, premium seating, and state-of-the-art sound systems.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$$$',
                'budget_label' => 'High',
                'budget_range' => '500-1500',
                'operating_hours' => [
                    'Monday' => '10:30 AM - 10:30 PM',
                    'Tuesday' => '10:30 AM - 10:30 PM',
                    'Wednesday' => '10:30 AM - 10:30 PM',
                    'Thursday' => '10:30 AM - 10:30 PM',
                    'Friday' => '10:30 AM - 11:00 PM',
                    'Saturday' => '10:30 AM - 10:30 PM',
                    'Sunday' => '10:30 AM - 8:00 PM',
                ],
                'average_rating' => 4.5,
                'total_reviews' => 310,
                'tags' => ['Movies', 'Multiplex', 'Dolly Atmos', 'Bashundhara City'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Blockbuster Cinemas',
                'category' => 'Cinema & Screenings',
                'area_name' => 'Kuril',
                'area_zone' => 'DNCC',
                'address' => 'Jamuna Future Park, Kuril, Dhaka',
                'description' => 'A massive multiplex located within Jamuna Future Park, featuring 7 themed theaters including a premium VIP lounge and 3D screens.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$$$',
                'budget_label' => 'High',
                'budget_range' => '600-2000',
                'operating_hours' => [
                    'Monday' => '11:00 AM - 11:00 PM',
                    'Tuesday' => '11:00 AM - 11:00 PM',
                    'Wednesday' => '11:00 AM - 11:00 PM',
                    'Thursday' => '11:00 AM - 11:00 PM',
                    'Friday' => '11:00 AM - 11:30 PM',
                    'Saturday' => '11:00 AM - 11:00 PM',
                    'Sunday' => '11:00 AM - 8:30 PM',
                ],
                'average_rating' => 4.5,
                'total_reviews' => 310,
                'tags' => ['Movies', 'Multiplex', '3D', 'JFP'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Jamuna Future Park',
                'category' => 'Shopping',
                'area_name' => 'Kuril',
                'area_zone' => 'DNCC',
                'address' => 'KA-244, Kuril, Pragati Sarani, Dhaka',
                'description' => 'The largest shopping mall in Bangladesh and one of the largest in the world. It features everything from global brands to an indoor theme park, bowling alley, and multiple swimming pools.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1561633442-f85764d0bc7b?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$$$',
                'budget_label' => 'Medium-High',
                'budget_range' => '500-50000',
                'operating_hours' => [
                    'Monday' => '11:00 AM - 9:00 PM',
                    'Tuesday' => '11:00 AM - 9:00 PM',
                    'Wednesday' => 'Closed',
                    'Thursday' => '11:00 AM - 9:00 PM',
                    'Friday' => '11:00 AM - 9:00 PM',
                    'Saturday' => '11:00 AM - 9:00 PM',
                    'Sunday' => '11:00 AM - 9:00 PM',
                ],
                'average_rating' => 4.3,
                'total_reviews' => 3200,
                'tags' => ['Super Mall', 'Theme Park', 'Bowling', 'Global Brands'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'New Market',
                'category' => 'Shopping',
                'area_name' => 'Azimpur',
                'area_zone' => 'DSCC',
                'address' => 'Mirpur Road, Dhaka',
                'description' => 'A historic and bustling traditional market. Famous for everything from books and stationery to clothing and household items at bargain prices.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$',
                'budget_label' => 'Low-Medium',
                'budget_range' => '50-5000',
                'operating_hours' => [
                    'Monday' => '10:00 AM - 9:00 PM',
                    'Tuesday' => 'Closed',
                    'Wednesday' => '10:00 AM - 9:00 PM',
                    'Thursday' => '10:00 AM - 9:00 PM',
                    'Friday' => '10:00 AM - 9:00 PM',
                    'Saturday' => '10:00 AM - 9:00 PM',
                    'Sunday' => '10:00 AM - 9:00 PM',
                ],
                'average_rating' => 4.2,
                'total_reviews' => 920,
                'tags' => ['Traditional', 'Bargain', 'Historic', 'Old School'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            // ─── ADDED PLACES TO MEET 5 PER CATEGORY ───
            [
                'name' => 'Toggi Fun World',
                'category' => 'Entertainment',
                'area_name' => 'Panthapath',
                'area_zone' => 'DNCC',
                'address' => 'Level 9-18, Bashundhara City, Dhaka',
                'description' => 'South Asia\'s largest vertical theme park, featuring virtual reality, escape rooms, and high-tech amusement rides for all ages.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$$$',
                'average_rating' => 4.6,
                'total_reviews' => 450,
                'tags' => ['Theme Park', 'VR', 'Family-Friendly', 'Indoor'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Fantasy Kingdom',
                'category' => 'Entertainment',
                'area_name' => 'Ashulia',
                'area_zone' => 'GD',
                'address' => 'Jamgora, Ashulia, Dhaka',
                'description' => 'The premier theme park of Bangladesh, featuring roller coasters, water kingdom, and heritage park.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1505159940484-eb2b9f2588e2?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$$$',
                'average_rating' => 4.4,
                'total_reviews' => 1200,
                'tags' => ['Theme Park', 'Water Park', 'Rides', 'Weekend Trip'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Nandan Park',
                'category' => 'Entertainment',
                'area_name' => 'Savar',
                'area_zone' => 'GD',
                'address' => 'Baripara, Nabinagar-Chandra Highway, Savar',
                'description' => 'A massive amusement park and water world set in a green landscape, perfect for family outings.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1545153996-e01b50d6f27d?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$$$',
                'average_rating' => 4.2,
                'total_reviews' => 850,
                'tags' => ['Amusement Park', 'Water World', 'Family', 'Outing'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Dhaka Shishu Park',
                'category' => 'Entertainment',
                'area_name' => 'Shahbagh',
                'area_zone' => 'DSCC',
                'address' => 'Shahbagh, Dhaka',
                'description' => 'The oldest and most iconic children\'s amusement park in the heart of Dhaka.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1531256379416-9f000e90aacc?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$',
                'average_rating' => 4.0,
                'total_reviews' => 3000,
                'tags' => ['Kids', 'Historic', 'Budget', 'Park'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Player\'s Island',
                'category' => 'Entertainment',
                'area_name' => 'Kuril',
                'area_zone' => 'DNCC',
                'address' => 'Jamuna Future Park, Dhaka',
                'description' => 'A modern bowling and arcade center featuring world-class lanes and the latest gaming consoles.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1544178170-6923bc8b9ca1?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$$',
                'average_rating' => 4.5,
                'total_reviews' => 600,
                'tags' => ['Bowling', 'Arcade', 'Gaming', 'Indoor'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Bangladesh National Museum',
                'category' => 'Culture',
                'area_name' => 'Shahbagh',
                'area_zone' => 'DSCC',
                'address' => 'Shahbagh Road, Dhaka',
                'description' => 'The premier museum of Bangladesh, housing a vast collection of historical, archaeological, and artistic artifacts.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1508919892451-41d5eb852528?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$',
                'average_rating' => 4.7,
                'total_reviews' => 2500,
                'tags' => ['History', 'Museum', 'Art', 'Heritage'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Liberation War Museum',
                'category' => 'Culture',
                'area_name' => 'Agargaon',
                'area_zone' => 'DNCC',
                'address' => 'Plot-F, 11/A-B, Sher-e-Bangla Nagar, Agargaon, Dhaka',
                'description' => 'A museum dedicated to the 1971 Independence War of Bangladesh, showcasing the struggle and sacrifice of the nation.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1518998053574-53f1f1172f23?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$',
                'average_rating' => 4.9,
                'total_reviews' => 1500,
                'tags' => ['History', 'Liberation War', 'Museum', 'Architecture'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Chhayanaut Autosh-shila Kendra',
                'category' => 'Culture',
                'area_name' => 'Dhanmondi',
                'area_zone' => 'DSCC',
                'address' => 'Road 15A, Dhanmondi, Dhaka',
                'description' => 'The epicenter of Bengali cultural music and tradition, famous for its Pohela Boishakh celebrations.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1514525253361-9f9311b058a5?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$$',
                'average_rating' => 4.8,
                'total_reviews' => 400,
                'tags' => ['Music', 'Culture', 'Traditional', 'Institution'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Bengal Shilpalay',
                'category' => 'Culture',
                'area_name' => 'Dhanmondi',
                'area_zone' => 'DSCC',
                'address' => 'House 42, Road 27, Dhanmondi, Dhaka',
                'description' => 'A sophisticated art gallery and cultural hub showcasing contemporary Bangladeshi art and crafts.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1493334241329-873859667746?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$$',
                'average_rating' => 4.6,
                'total_reviews' => 200,
                'tags' => ['Art', 'Gallery', 'Exhibitions', 'Crafts'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Baldha Garden',
                'category' => 'Outdoors',
                'area_name' => 'Wari',
                'area_zone' => 'DSCC',
                'address' => 'Wari, Old Dhaka',
                'description' => 'One of the oldest botanical gardens in the region, featuring rare plant species and a peaceful historic atmosphere.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$',
                'average_rating' => 4.1,
                'total_reviews' => 500,
                'tags' => ['Botanical', 'Garden', 'Historic', 'Nature'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'National Botanical Garden',
                'category' => 'Outdoors',
                'area_name' => 'Mirpur',
                'area_zone' => 'DNCC',
                'address' => 'Zoo Road, Mirpur-2, Dhaka',
                'description' => 'The largest plant conservation center in Bangladesh, sprawling over 200 acres with thousands of species.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1598902108854-10e335adac99?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$',
                'average_rating' => 4.3,
                'total_reviews' => 3000,
                'tags' => ['Nature', 'Park', 'Botanical', 'Outing'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Ramna Park',
                'category' => 'Outdoors',
                'area_name' => 'Shahbagh',
                'area_zone' => 'DSCC',
                'address' => 'Shahbagh, Dhaka',
                'description' => 'The historic green lung of Dhaka city, known for its large lake and diverse flora.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$',
                'average_rating' => 4.5,
                'total_reviews' => 5000,
                'tags' => ['Park', 'Jogging', 'Historic', 'Lake'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Star Cineplex (SKS Tower)',
                'category' => 'Cinema & Screenings',
                'area_name' => 'Mohakhali',
                'area_zone' => 'DNCC',
                'address' => 'SKS Tower, Mohakhali, Dhaka',
                'description' => 'A premium multiplex experience in the heart of Mohakhali, offering the latest international and local films.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1517604401157-53c7016fd8da?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$$$',
                'average_rating' => 4.7,
                'total_reviews' => 350,
                'tags' => ['Movies', 'Multiplex', 'Luxury', 'Mohakhali'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Star Cineplex (Sony Square)',
                'category' => 'Cinema & Screenings',
                'area_name' => 'Mirpur',
                'area_zone' => 'DNCC',
                'address' => 'Sony Square, Mirpur-2, Dhaka',
                'description' => 'State-of-the-art cinema screens bringing the multiplex experience to the Mirpur community.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1595769816263-9b910be24d5f?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$$$',
                'average_rating' => 4.6,
                'total_reviews' => 420,
                'tags' => ['Movies', 'Multiplex', 'Mirpur', '3D'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Lion Cinemas',
                'category' => 'Cinema & Screenings',
                'area_name' => 'Old Dhaka',
                'area_zone' => 'DSCC',
                'address' => 'Lion Shoppers World, Old Dhaka',
                'description' => 'Bringing the modern cinema experience to the historic streets of Old Dhaka.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$$',
                'average_rating' => 4.3,
                'total_reviews' => 150,
                'tags' => ['Movies', 'Old Dhaka', 'Multiplex'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Aarong (Uttara Flagship)',
                'category' => 'Shopping',
                'area_name' => 'Uttara',
                'area_zone' => 'DNCC',
                'address' => 'Sector 3, Uttara, Dhaka',
                'description' => 'The flagship store of Bangladesh\'s most iconic lifestyle brand, showcasing premium handicrafts and apparel.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$$$',
                'average_rating' => 4.8,
                'total_reviews' => 1200,
                'tags' => ['Lifestyle', 'Handicraft', 'Premium', 'Traditional'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Eastern Plaza',
                'category' => 'Shopping',
                'area_name' => 'Hatirpool',
                'area_zone' => 'DSCC',
                'address' => 'Hatirpool, Dhaka',
                'description' => 'One of the city\'s most famous hubs for electronics, mobile phones, and fashion accessories.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$$',
                'average_rating' => 4.1,
                'total_reviews' => 2000,
                'tags' => ['Electronics', 'Mobiles', 'Fashion', 'Historic Mall'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Curzon Hall',
                'category' => 'Landmarks & Heritage',
                'area_name' => 'Shahbagh',
                'area_zone' => 'DSCC',
                'address' => 'Dhaka University, Dhaka',
                'description' => 'A magnificent blend of Mughal and European architecture, serving as the home of the science faculty of Dhaka University.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$',
                'average_rating' => 4.9,
                'total_reviews' => 1200,
                'tags' => ['Architecture', 'University', 'History', 'Landmark'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Tara Masjid (Star Mosque)',
                'category' => 'Landmarks & Heritage',
                'area_name' => 'Old Dhaka',
                'area_zone' => 'DSCC',
                'address' => 'Armanitola, Dhaka',
                'description' => 'An exquisitely decorated mosque known for its star patterns and ornate mosaic work.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$',
                'average_rating' => 4.7,
                'total_reviews' => 600,
                'tags' => ['Mosque', 'Architecture', 'Mosaic', 'Historic'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Sultan\'s Dine',
                'category' => 'Food & Drinks',
                'area_name' => 'Dhanmondi',
                'area_zone' => 'DSCC',
                'address' => 'Satmasjid Road, Dhanmondi, Dhaka',
                'description' => 'The ultimate destination for Kacchi Biryani lovers in Dhaka, famous for its rich flavors and generous portions.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1563379091339-03b21bc4a4f8?auto=format&fit=crop&w=1200&q=80',
                'budget_tier' => '$$',
                'average_rating' => 4.8,
                'total_reviews' => 3500,
                'tags' => ['Biryani', 'Kacchi', 'Foodie', 'Local Favorite'],
                'is_published' => true,
                'created_by' => $admin->id,
            ],
        ];

        foreach ($places as $v) {
            Place::create($v);
        }

        // ─── REAL DHAKA EVENTS ───
        $events = [
            [
                'title' => 'Ekushey Boi Mela 2026',
                'slug' => 'ekushey-boi-mela-2026',
                'category' => 'Culture',
                'area_name' => 'Bangla Academy',
                'area_zone' => 'DSCC',
                'organiser_name' => 'Bangla Academy',
                'description' => 'The nation\'s biggest book fair, held every February to commemorate the Language Movement martyrs. Over 500 publishers set up stalls across the Bangla Academy grounds and Suhrawardy Udyan.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1491841573634-28140fc7ced7?auto=format&fit=crop&w=1200&q=80',
                'event_date' => '2026-04-20',
                'end_date' => '2026-05-20',
                'start_time' => '03:00 PM',
                'end_time' => '09:00 PM',
                'average_rating' => 4.8,
                'total_reviews' => 2400,
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'title' => 'Dhaka Lit Fest 2026',
                'slug' => 'dhaka-lit-fest-2026',
                'category' => 'Culture',
                'area_name' => 'Bangla Academy',
                'area_zone' => 'DSCC',
                'organiser_name' => 'Dhaka Lit Fest Foundation',
                'description' => 'South Asia\'s most prestigious English-language literary festival. Featuring over 200 speakers across 100+ sessions — panel discussions, readings, book launches, and performances.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=1200&q=80',
                'event_date' => '2026-11-14',
                'end_date' => '2026-11-16',
                'start_time' => '10:00 AM',
                'end_time' => '08:00 PM',
                'average_rating' => 4.9,
                'total_reviews' => 1800,
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'title' => 'Pohela Boishakh 1433',
                'slug' => 'pohela-boishakh-1433',
                'category' => 'Culture',
                'area_name' => 'Ramna Boothomul',
                'area_zone' => 'DSCC',
                'organiser_name' => 'Chhayanaut',
                'description' => 'The Bengali New Year celebrations at Ramna Botomul — Dhaka\'s most cherished cultural tradition.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1767330855011-fc628d33caea?auto=format&fit=crop&w=1200&q=80',
                'event_date' => '2026-04-27',
                'end_date' => '2026-04-27',
                'start_time' => '06:00 AM',
                'end_time' => '10:00 PM',
                'average_rating' => 4.9,
                'total_reviews' => 5100,
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'title' => 'Spring Street Food Festival',
                'slug' => 'spring-food-fest-2026',
                'category' => 'Food & Drinks',
                'area_name' => 'Banani',
                'area_zone' => 'DNCC',
                'organiser_name' => 'Chef\'s Table',
                'description' => 'A 10-day celebration of Dhaka\'s vibrant street food culture with over 50 vendors from across the city.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1729941506359-cf4924f023e5?auto=format&fit=crop&w=1200&q=80',
                'event_date' => '2026-04-20',
                'end_date' => '2026-04-30',
                'start_time' => '12:00 PM',
                'end_time' => '11:00 PM',
                'average_rating' => 4.5,
                'total_reviews' => 120,
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'title' => 'Contemporary Art Exhibit',
                'slug' => 'contemporary-art-2026',
                'category' => 'Culture',
                'area_name' => 'Dhanmondi',
                'area_zone' => 'DSCC',
                'organiser_name' => 'Dhaka Art Center',
                'description' => 'Showcasing the latest works by emerging artists from across Bangladesh.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?auto=format&fit=crop&w=1200&q=80',
                'event_date' => '2026-04-22',
                'end_date' => '2026-05-05',
                'start_time' => '10:00 AM',
                'end_time' => '08:00 PM',
                'average_rating' => 4.7,
                'total_reviews' => 45,
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'title' => 'Rock Dhaka 2026',
                'slug' => 'rock-dhaka-2026',
                'category' => 'Entertainment',
                'area_name' => 'International Convention City Bashundhara',
                'area_zone' => 'DNCC',
                'organiser_name' => 'LiveSquare Entertainment',
                'description' => 'The biggest rock concert of the year featuring top bands of Bangladesh.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&w=1200&q=80',
                'event_date' => '2026-05-15',
                'end_date' => '2026-05-15',
                'start_time' => '04:00 PM',
                'end_time' => '11:00 PM',
                'average_rating' => 0,
                'total_reviews' => 0,
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'title' => 'Heritage Walk: Mughal Dhaka',
                'slug' => 'heritage-walk-mughal-dhaka',
                'category' => 'Landmarks & Heritage',
                'area_name' => 'Old Dhaka',
                'area_zone' => 'DSCC',
                'organiser_name' => 'Urban Explorers',
                'description' => 'A guided evening tour through the historic lanes of Puran Dhaka, visiting Lalbagh Fort and Ahsan Manzil under the stars.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&w=1200&q=80',
                'event_date' => '2026-04-26',
                'end_date' => '2026-04-28',
                'start_time' => '05:00 PM',
                'end_time' => '09:00 PM',
                'average_rating' => 4.8,
                'total_reviews' => 120,
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'title' => 'Hatirjheel Monsoon Boat Parade',
                'slug' => 'hatirjheel-boat-parade',
                'category' => 'Outdoors',
                'area_name' => 'Tejgaon',
                'area_zone' => 'DNCC',
                'organiser_name' => 'RAJUK',
                'description' => 'A festive parade of decorated traditional and modern boats in the heart of Dhaka\'s favorite water body.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1559131355-667240c5f403?auto=format&fit=crop&w=1200&q=80',
                'event_date' => '2026-07-15',
                'end_date' => '2026-07-15',
                'start_time' => '04:30 PM',
                'end_time' => '07:30 PM',
                'average_rating' => 4.6,
                'total_reviews' => 85,
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'title' => 'Dhanmondi Open Air Film Fest',
                'slug' => 'dhanmondi-open-air-film',
                'category' => 'Cinema & Screenings',
                'area_name' => 'Dhanmondi',
                'area_zone' => 'DSCC',
                'organiser_name' => 'Movie Buffs Dhaka',
                'description' => 'Experience cinema under the moonlight at Rabindra Sarobar with screenings of classic and contemporary Bangladeshi films.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1595769816263-9b910be24d5f?auto=format&fit=crop&w=1200&q=80',
                'event_date' => '2026-05-20',
                'end_date' => '2026-05-22',
                'start_time' => '06:30 PM',
                'end_time' => '10:30 PM',
                'average_rating' => 4.9,
                'total_reviews' => 210,
                'is_published' => true,
                'created_by' => $admin->id,
            ],
            [
                'title' => 'Eid Shopping Grand Expo',
                'slug' => 'eid-shopping-expo-2026',
                'category' => 'Shopping',
                'area_name' => 'Kuril',
                'area_zone' => 'DNCC',
                'organiser_name' => 'Jamuna Future Park',
                'description' => 'The biggest shopping festival of the year, featuring massive discounts, lucky draws, and exclusive launches from top brands.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1200&q=80',
                'event_date' => '2026-05-05',
                'end_date' => '2026-05-15',
                'start_time' => '10:00 AM',
                'end_time' => '10:00 PM',
                'average_rating' => 4.5,
                'total_reviews' => 560,
                'is_published' => true,
                'created_by' => $admin->id,
            ],
        ];

        foreach ($events as $e) {
            Event::create($e);
        }

        // ─── SEED SOME REVIEWS ───
        $reviewData = [
            ['place_id' => 1, 'user_id' => $user->id, 'rating' => 5, 'body' => 'Best specialty coffee in Dhaka, hands down. The Ethiopian single-origin pour-over was phenomenal.'],
            ['place_id' => 1, 'user_id' => $user2->id, 'rating' => 4, 'body' => 'Great ambiance for working. WiFi is reliable and the cold brew is solid. Can get crowded on weekends.'],
            ['place_id' => 2, 'user_id' => $user->id, 'rating' => 5, 'body' => 'The lakeside terrace at sunset is magical. Mango smoothie is a must-try. Perfect brunch spot.'],
            ['place_id' => 2, 'user_id' => $user3->id, 'rating' => 4, 'body' => 'Love the vibe here. Affordable for students. The pasta could use improvement though.'],
            ['place_id' => 3, 'user_id' => $user2->id, 'rating' => 5, 'body' => 'The mutton biriyani here is genuinely the best I have ever had. A Dhaka institution. Come early or it sells out.'],
            ['place_id' => 3, 'user_id' => $user3->id, 'rating' => 5, 'body' => 'Five generations of perfection. The naan-e-kabab is otherworldly. Old Dhaka at its finest.'],
            ['place_id' => 4, 'user_id' => $user->id, 'rating' => 5, 'body' => 'Walking through the Mughal corridors at dawn was breathtaking. The gardens are so well maintained.'],
            ['place_id' => 4, 'user_id' => $user2->id, 'rating' => 4, 'body' => 'Beautifully preserved. The Tomb of Bibi Pari is hauntingly beautiful. Wish the museum had more English signage.'],
            ['place_id' => 5, 'user_id' => $user3->id, 'rating' => 5, 'body' => 'The Pink Palace at dusk, lit up against the Buriganga — absolutely stunning. Great little museum too.'],
            ['place_id' => 6, 'user_id' => $user->id, 'rating' => 4, 'body' => 'Best place in Dhaka for an evening walk. The bridge is beautifully lit. Street food vendors are a bonus.'],
            ['place_id' => 7, 'user_id' => $user2->id, 'rating' => 4, 'body' => 'Peaceful morning jog around the lake. The renovated walkways are great. Gets very crowded evenings.'],
            ['place_id' => 11, 'user_id' => $user->id, 'rating' => 5, 'body' => 'Louis Kahn\'s masterpiece. You feel the weight of history and architecture simultaneously. The grounds are perfect for photography.'],
            ['place_id' => 12, 'user_id' => $user3->id, 'rating' => 5, 'body' => 'Incredible live music under the stars. The acoustic sessions on Friday nights are not to be missed.'],
        ];

        foreach ($reviewData as $r) {
            Review::create([
                ...$r,
                'reviewable_type' => 'place',
            ]);
        }

        // ─── BLOG POSTS ───
        $posts = [
            [
                'title' => 'Best Rooftop Cafés in Dhanmondi',
                'slug' => 'best-rooftop-cafes-in-dhanmondi',
                'featured_image_url' => 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=1200&q=80',
                'body' => "Dhanmondi has quietly become Dhaka's rooftop café capital. Perched above the city's leafy aplaces, these sky-high spots offer stunning views alongside world-class coffee and locally sourced bites.\n\n## Why Rooftops?\n\nDhaka's urban heat makes a breezy rooftop the ultimate escape. When the sun dips below the horizon, these terraces transform into social hubs buzzing with conversations, live acoustic sets, and the warm glow of string lights.\n\n## Our Top 5 Picks\n\n**1. The Perch** — Nestled above Satmasjid Road, The Perch serves specialty pour-overs and mezze platters as you look out over Lake Dhanmondi. A must-visit on weekend evenings.\n\n**2. Sky Garden Café** — A verdant rooftop paradise with hanging ferns and ambient lighting. Their cold brew and banana bread are legendary in the neighbourhood.\n\n**3. Altitude Lounge** — More upscale, Altitude caters to professionals unwinding after work. Think craft cocktails and sushi platters against the glittering city skyline.\n\n**4. Chai Stories** — For the tea enthusiast, Chai Stories curates 40+ single-origin blends alongside homemade snacks. Their evening storytelling sessions are a community favourite.\n\n**5. Roofscape** — The newest addition to the Dhanmondi scene, Roofscape prioritises local art. Gallery walls line the terrace perimeter, with rotating exhibitions every month.",
                'tags' => ['Rooftop', 'Café', 'Dhanmondi', 'Food & Drinks'],
            ],
            [
                'title' => 'A Night Out in Old Dhaka',
                'slug' => 'a-night-out-in-old-dhaka',
                'featured_image_url' => 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
                'body' => "Old Dhaka doesn't sleep. As the rest of the city winds down, Puran Dhaka comes alive — its narrow alleys filling with the clatter of rickshaws, the sizzle of biriani pots, and the laughter of friends gathering around centuries-old tea stalls.\n\n## Starting Your Evening\n\nBegin at **Chawkbazar** as dusk sets in. This ancient marketplace has been the heart of Old Dhaka trade for over 400 years.\n\n## The Food Trail\n\nNo night in Puran Dhaka is complete without a pilgrimage to **Haji Biriani** on Nalgola Road. Their 100-year-old recipe of slow-cooked mutton biriani is the stuff of legend.\n\n## Walking Ahsan Manzil at Dusk\n\nThe Pink Palace glows under floodlights against the Buriganga River. An evening stroll along the ghats here offers an entirely different perspective of Dhaka: quieter, contemplative, beautiful.",
                'tags' => ['Heritage', 'Food', 'Old Dhaka', 'Night Out'],
            ],
        ];

        foreach ($posts as $post) {
            BlogPost::create([
                ...$post,
                'author_id' => $admin->id,
                'is_published' => true,
                'published_at' => now()->subDays(rand(1, 20)),
            ]);
        }

        // ─── FINAL SYNC ───
        // Recalculate ratings and counts for all places and events to ensure accuracy
        Place::all()->each(function($place) {
            $reviews = Review::where('place_id', $place->id);
            $place->average_rating = $reviews->avg('rating') ?: 0;
            $place->total_reviews = $reviews->count();
            $place->save();
        });
        
        Event::all()->each(function($event) {
            $reviews = Review::where('event_id', $event->id);
            $event->average_rating = $reviews->avg('rating') ?: 0;
            $event->total_reviews = $reviews->count();
            $event->save();
        });
    }
}
